import type { BlogPost } from "./types";

/**
 * Instructor-curated digests. Intros paraphrase the official posts only —
 * never invent news, quotes, or dates. Source URLs are the originals.
 */
export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "nextjs-v0-instant-navigations-agent",
    title: "Making v0 navigations instant with Next.js 16.3 and an agent loop",
    publishedAt: "2026-09-30T12:00:00.000Z",
    tags: ["nextjs", "ai", "course"],
    relatedChapters: ["ch1"],
    intro: [
      "On August 6, 2026, the Next.js blog described Instant Navigations in 16.3. They help dynamic App Router apps feel snappy without moving data-fetching to the client: Suspense loading states or 'use cache' let Next extract a shell and load it into the browser before navigation, a Partial Prerendering-style approach for personalized apps.",
      "The Next.js team adopted this in v0, Vercel's full-stack coding platform, using a coding agent and the next-cache-components-optimizer Skill. For each slow journey the agent wrote a failing Playwright test with the instant() helper from @next/playwright, applied Skill patterns, re-ran until green, and kept the tests in CI. One refactor moves session and team fetches under Suspense so the settings shell stays instant. Install the Skill with npx skills add vercel/next.js --skill next-cache-components-optimizer, then prompt agents to make a named navigation instant.",
      "The post closes on a simple point: frameworks still matter in the agent era because helpers like instant() turn fuzzy UX into deterministic tests. That App Router work sits on the same Vercel deploy path as Chapter 1.",
    ],
    source: {
      title: "Making Navigations Instant in v0",
      url: "https://nextjs.org/blog/making-v0-navigations-instant",
      publisher: "Next.js",
    },
  },
  {
    slug: "cursor-agent-token-efficiency",
    title: "Cursor cut agent token costs 7% without hurting quality",
    publishedAt: "2026-09-30T12:00:00.000Z",
    tags: ["ai", "course"],
    relatedChapters: ["ch1"],
    intro: [
      "On September 23, 2026, Jediah Katz, Connor O'Keefe, and Calvin Yee wrote that longer agent runs spend more on context. Cursor improved harness efficiency and reduced user token costs about 7% without reducing agent quality.",
      "They trimmed roughly 66% of the system prompt as models needed less hand-holding. Dynamic tool loading extends an earlier MCP idea: tools-as-dynamic-context cut tokens about 46.9% in sessions that called MCP, and the same idea for built-in tools cut static-context description tokens about 60%, while high-frequency read, search, edit, and shell tools stay static. Explicit prompt-cache breakpoints, available with the OpenAI API since GPT-5.6, plus moving variable setup into a phantom user message, cut cold cache misses about 20%. Line numbers on file reads only every tenth line meant about 1.6% fewer cache-read tokens. Subagent prompting and model selection were tightened to avoid an unnecessary coordination tax.",
      "Those harness choices sit next to the Chapter 1 tooling you use when shipping apps with AI-assisted workflows.",
    ],
    source: {
      title: "Improved token efficiency for longer agent runs",
      url: "https://cursor.com/blog/improved-token-efficiency",
      publisher: "Cursor",
    },
  },
  {
    slug: "memtensor-sckit-npm-pypi-worm",
    title: "MemTensor npm/PyPI packages shipped a supplychain.local Go worm",
    publishedAt: "2026-09-30T12:00:00.000Z",
    tags: ["security", "course"],
    relatedChapters: ["ch1", "ch5"],
    intro: [
      "On September 23, 2026, updated September 24, Oliver Smith at Aikido reported compromised packages that already had a benign history: npm @memtensor/memos-cloud-openclaw-plugin versions >=0.1.21 and PyPI MemoryOS >=2.0.34. The worm, tracked as supplychain.local, ships multiplatform Golang sckit binaries launched by language-native loaders when the package is used, not through install-time scripts.",
      "Droppers spawn the platform binary with stage0 --config64 and a base64 config pointing at skyleen.fr C2 fronts. It is designed to self-propagate through stolen publish credentials (npm publish and twine) and GitHub Actions templates, and it hunts for GitHub, GitLab, npm, PyPI, AWS, Vault, Slack, and other secrets. Check lockfiles and installs for those versions, and treat runtime package-use paths as the risk, not only install hooks.",
      "That package hygiene is the same Node dependency work as Chapter 5, on the full-stack stack you meet in Chapter 1.",
    ],
    source: {
      title: "Novel supplychain.local Go worm appears",
      url: "https://www.aikido.dev/blog/supplychain-local-memtensor-npm-pypi",
      publisher: "Aikido",
    },
  },
  {
    slug: "ai-sdk-software-factory",
    title: "Vercel built a software factory that authors AI SDK PRs",
    publishedAt: "2026-09-29T12:00:00.000Z",
    tags: ["ai", "course"],
    relatedChapters: ["ch1"],
    intro: [
      "On August 12, 2026, Lars Grammel and Eric Dodds explained how the AI SDK team built ai-sdk-factory after the repo piled up over 1,000 open issues and nearly 800 pull requests. Dedicated agents classify issues, reproduce bugs, analyze features, implement changes, review PRs, update docs, and open backports — each agent scoped to one task with its own prompts and evals. Humans still merge every change.",
      "Security is built in from the second agent onward: every run happens in an isolated Vercel Sandbox with only the secrets that task needs, plus a network shield so untrusted issue or PR content cannot exfiltrate credentials. Four weeks into production the factory authored about 25–35% of merged mainline PRs, more than half of weekly v5/v6 backport merges, and closed over 75% of July issues while shrinking the open-issue peak.",
      "Agent-assisted maintenance of the TypeScript AI stack sits beside the same Vercel and Next.js tooling you use in Chapter 1.",
    ],
    source: {
      title: "Building a software factory for AI SDK",
      url: "https://vercel.com/blog/building-a-software-factory-for-ai-sdk",
      publisher: "Vercel",
    },
  },
  {
    slug: "vercel-sandbox-network-boundary",
    title: "Sandbox egress control: half a sandbox without a network boundary",
    publishedAt: "2026-09-29T12:00:00.000Z",
    tags: ["security", "ai", "course"],
    relatedChapters: ["ch1", "ch5"],
    intro: [
      "On August 11, 2026, Brandon Tuttle argued that compute isolation alone is only half a sandbox for agent workloads. A microVM can keep untrusted code off the host, but without egress control that code can still exfiltrate data, probe internal services, or abuse credentials available inside the environment. Recent research shows a forgotten DNS path or fail-open allowlist can defeat containment without crossing the VM boundary.",
      "Vercel Sandbox enforces the network boundary on the host outside the microVM: domain and CIDR policies, SNI inspection for TLS destinations, DNS filtered with the same rules, credential injection at the firewall so API keys never enter the sandbox, and optional request forwarding through your own proxy with a Vercel OIDC identity. Policies can open, narrow, and deny connectivity while a sandbox is running — for example allow a registry during setup, then deny-all before generated code runs.",
      "Those Node-side secrets and sandbox boundaries matter for the same server and deploy path you meet in Chapter 5 and Chapter 1.",
    ],
    source: {
      title: "A sandbox without a network boundary is only half a sandbox",
      url: "https://vercel.com/blog/a-sandbox-without-a-network-boundary-is-only-half-a-sandbox",
      publisher: "Vercel",
    },
  },
  {
    slug: "vercel-workflow-sdk-programming-language",
    title: "Workflow SDK: durable TypeScript without a new orchestrator",
    publishedAt: "2026-09-29T12:00:00.000Z",
    tags: ["nextjs", "ai", "course"],
    relatedChapters: ["ch1", "ch5"],
    intro: [
      "On August 27, 2026, Pranay Prakash described Workflow SDK as durable execution that feels like ordinary TypeScript instead of a hand-drawn DAG. Mark an orchestrator with use workflow and side-effecting work with use step; between them you keep await, try/catch, Promise.all, loops, and conditionals. The compiler splits that one file into workflow and step bundles, retries uncaught errors by default, and replaces Temporal-style signals/queries/updates with a single hook primitive — including createWebhook() for an ad-hoc URL that parks a run until someone POSTs.",
      "The post frames Workflow SDK as a library, not a platform: the runtime talks to a swappable World for storage, queuing, auth, and streaming (Postgres, Redis, Kafka, Vercel Queues, and more). On Vercel, each run pins to the immutable deployment that started it so changing workflow code does not break in-flight runs. Workflow v5 (beta) is said to cut step overhead substantially, with the long-term goal that steps feel free.",
      "That durable server work sits next to the Node and App Router path you take in Chapter 5 and Chapter 1 when you ship full-stack apps on Vercel.",
    ],
    source: {
      title: "The best workflow engine is a programming language",
      url: "https://vercel.com/blog/the-best-workflow-engine-is-a-programming-language",
      publisher: "Vercel",
    },
  },
  {
    slug: "nextjs-16-3-app-like-experiences",
    title: "Next.js 16.3: Instant Navigations for app-like UX",
    publishedAt: "2026-09-28T12:00:00.000Z",
    tags: ["nextjs", "react", "course"],
    relatedChapters: ["ch1"],
    intro: [
      "Next.js published a walkthrough of Instant Navigations in 16.3, built on Cache Components and Partial Prefetching. Cache Components keep a route ready with static, cached, and fallback UI; Partial Prefetching fetches that App Shell for visible Link components before a click. The post demos the pattern in Next Beats, Drop, Flow, and Huddle — music, social, calendar, and chat apps that feel like SPAs while still rendering on the server.",
      "The guide covers caching with 'use cache' and cacheLife/cacheTag, prefetch={true} for URL-specific content, Client Component islands with shared providers, revalidation via updateTag after Server Actions, experimental offline retry with useOffline, nested Suspense for stable streaming, useTransition/useOptimistic for mutations, and React View Transitions for reveals and route slides. The demos are open source with Playwright tests using the instant() helper.",
      "That App Router navigation and caching story is the same Next.js path you start from in Chapter 1.",
    ],
    source: {
      title: "Building App-like Experiences with Next.js 16.3",
      url: "https://nextjs.org/blog/building-app-like-experiences-with-nextjs-16-3",
      publisher: "Next.js",
    },
  },
  {
    slug: "state-of-agent-skills-one-million",
    title: "State of agent skills: 1M skills and 280M installs on skills.sh",
    publishedAt: "2026-09-28T12:00:00.000Z",
    tags: ["ai", "course"],
    relatedChapters: ["ch1"],
    intro: [
      "On September 25, 2026, Amelia Charles, Andrew Qu, and Jonathan Hefner reported that Vercel's skills.sh registry reached one million agent skills and nearly 280 million installs in seven months. A skill is reusable instructions that teach an AI agent how a specific person, team, or company does a job — often plain language — so agents stop being generic and start matching local practice.",
      "Using aggregate registry data, the report finds supply leans technical (software engineering about a quarter of listings) while demand is broader: software engineering leads installs at 18%, then agent workflows at 15%, with business operations and writing near 11% each. Installs are concentrated — the top 375 skills (0.04% of the registry) account for 62% of installs — and seven in eight installs go to cross-industry skills. The authors argue the next wave will encode company-specific judgment, with effectiveness measured by tests rather than popularity alone.",
      "Agent skills sit next to the same Vercel and Next.js tooling you use in Chapter 1 when you ship full-stack apps.",
    ],
    source: {
      title: "State of agent skills",
      url: "https://vercel.com/blog/state-of-agent-skills",
      publisher: "Vercel",
    },
  },
  {
    slug: "tanstack-query-codegen-supply-chain-worm",
    title: "TanStack Query OpenAPI codegen hit by npm supply-chain worm",
    publishedAt: "2026-09-28T12:00:00.000Z",
    tags: ["security", "react", "course"],
    relatedChapters: ["ch1", "ch5"],
    intro: [
      "On August 28, 2026, Ilyas Makari at Aikido reported that ten versions of @7nohe/openapi-react-query-codegen (a popular generator of type-safe TanStack Query hooks from OpenAPI, 150k+ weekly downloads) were published to npm in about 20 minutes with malware branded Trinitite. Both the npm package and GitHub repo were compromised via a GitHub Actions workflow vulnerability, so releases still carried valid provenance attestations from the official workflow.",
      "Install-time execution used a binding.gyp Python sandbox escape (and sometimes a preinstall script) to run a multi-megabyte Node payload that harvests GitHub, npm, cloud, and local credentials, exfiltrates encrypted bundles to public GitHub repos, and worms into other packages the stolen tokens can publish. Aikido lists the affected version numbers and file hashes; check whether those versions appear in lockfiles and rotate tokens if they do.",
      "Dependency hygiene on npm packages is the same Node server and package work as Chapter 5, on the React data-fetching stack you meet alongside Chapter 1.",
    ],
    source: {
      title: "Popular code generator for TanStack Query hit by supply chain worm",
      url: "https://www.aikido.dev/blog/popular-code-generator-for-tanstack-query-hit-by-supply-chain-worm",
      publisher: "Aikido",
    },
  },
  {
    slug: "klaviyo-356-internal-apps-vercel",
    title: "Klaviyo: 356 internal apps in two weeks on Vercel",
    publishedAt: "2026-09-25T12:00:00.000Z",
    tags: ["nextjs", "ai", "course"],
    relatedChapters: ["ch1"],
    intro: [
      "On September 24, 2026, Susan Aziz and Kevin Sundstrom described how Klaviyo built a platform on Vercel for shipping internal apps, then opened it through a citizen developer program. In the first two weeks, 512 of Klaviyo's more than 2,000 employees deployed 356 apps; 196 were full-stack apps with their own databases. Teams now shipping include legal, marketing, and HR.",
      "Secure Compute gives deployments a private network path into Klaviyo's infrastructure so apps can use company databases without public internet traffic. Apps are SSO-gated through Okta via Enterprise Managed Users, sensitive environment variables sit at the team level, and Wiz scans feed the SIEM. K:Forge, built on the Vercel SDK, creates a GitHub repo, deploys on Vercel, connects data, and applies security defaults so builders go from idea to a live app in under three minutes.",
      "That deploy path is the same Vercel platform you already use in Chapter 1.",
    ],
    source: {
      title: "How Klaviyo shipped 356 internal apps in two weeks on Vercel",
      url: "https://vercel.com/blog/how-klaviyo-shipped-356-internal-apps-in-two-weeks-on-vercel",
      publisher: "Vercel",
    },
  },
  {
    slug: "vercel-connect-credential-sprawl-ga",
    title: "Vercel Connect GA: short-lived tokens instead of credential sprawl",
    publishedAt: "2026-09-25T12:00:00.000Z",
    tags: ["ai", "security", "course"],
    relatedChapters: ["ch1", "ch5"],
    intro: [
      "On August 25, 2026, Hedi Zandi, Ben Sabic, and Dima Voytenko announced that Vercel Connect is generally available. Connect replaces long-lived provider tokens with short-lived ones your code requests at runtime, scoped to the task. During the public beta the ecosystem grew past 100 connectors.",
      "Apps register a connector once, attach it to projects, and call getToken at runtime; deployments use OIDC identity so there is no provider secret to commit. GA adds fine-grained RBAC for who manages connectors, audit logs, and token and trigger observability. Triggers forward provider events with server-side signature verification so webhook signing secrets stay out of the app. Hobby includes 500 token requests and 1,000 triggers per month; Pro is billed at $3 per 1,000 token requests and $0.95 per 1,000 triggers, with beta billing terms unchanged until September 25, 2026.",
      "Keeping secrets out of the app fits the Node server work in Chapter 5 and the same Vercel deploy path as Chapter 1.",
    ],
    source: {
      title: "The end of credential sprawl for agents",
      url: "https://vercel.com/blog/the-end-of-credential-sprawl-for-agents",
      publisher: "Vercel",
    },
  },
  {
    slug: "vercel-bug-bounty-public",
    title: "Vercel Bug Bounty Program is now public on HackerOne",
    publishedAt: "2026-09-25T12:00:00.000Z",
    tags: ["security", "course"],
    relatedChapters: ["ch1", "ch5"],
    intro: [
      "On September 24, 2026, Caleb An and Talha Tariq announced that Vercel is combining its private and open-source bounty programs into a single public Vercel bug bounty program on HackerOne. Earlier public efforts named in the post include the $1 million React2Shell hacker challenge, the $1 million Vercel Sandbox hacker challenge, and the OSS bug bounty program.",
      "All products across the Vercel platform and open-source projects are in scope. New OSS findings go to the main program; existing OSS submissions do not need to be copied over. The post says AI has increased both valid and invalid reports, and that Vercel streamlined triage tooling rather than closing the program. Researchers submit through HackerOne with clear reproduction steps.",
      "That disclosure path is the same platform security hygiene as Chapter 1 and the Node dependency work in Chapter 5.",
    ],
    source: {
      title: "The Vercel Bug Bounty Program is now publicly available",
      url: "https://vercel.com/blog/the-vercel-bug-bounty-program-is-now-publicly-available",
      publisher: "Vercel",
    },
  },
  {
    slug: "turbopack-chunking-nextjs-16-3",
    title: "Turbopack chunking: fewer requests without over-shipping JS",
    publishedAt: "2026-09-24T12:00:00.000Z",
    tags: ["nextjs", "course"],
    relatedChapters: ["ch1"],
    intro: [
      "On September 3, 2026, Next.js explained how Turbopack decides which code goes in which JavaScript file. One big chunk earns cache hits but over-ships; one chunk per page duplicates shared code; one chunk per module creates too many requests. Turbopack merges smaller chunks within a chunk group, the chunks loaded together for a route.",
      "On nextjs.org demo navigations, no merging was 561.6 KiB and 96 requests, Turbopack defaults were 554.8 KiB and 38 requests, and one chunk per group was 610.0 KiB and 15 requests. In Next.js 16.3, experimental.turbopackChunking.generateComponentChunks emits un-merged versions so the runtime can load only the missing pieces on soft navigations. The same experimental.turbopackChunking options include firstPageLoadPriority, priorityRoutes, and clusters. experimental.turbopackCjsTreeShaking covers CommonJS tree-shaking, and experimental.turbopackSharedRuntime saves about 10 KB after the first navigation.",
      "That chunking is part of the App Router and Next.js tooling in Chapter 1.",
    ],
    source: {
      title: "How Turbopack chunks your JavaScript",
      url: "https://nextjs.org/blog/turbopack-chunking",
      publisher: "Next.js",
    },
  },
  {
    slug: "nextjs-closed-1500-github-issues-agent",
    title: "Next.js closed 1,462 issues with a read-only closability agent",
    publishedAt: "2026-09-24T12:00:00.000Z",
    tags: ["ai", "nextjs", "course"],
    relatedChapters: ["ch1"],
    intro: [
      "The Next.js issue backlog peaked at 3,109 open reports in January 2025 and still had 2,244 on August 10, 2026. On September 4, 2026, the team described closability, built on eve, Vercel's open-source agent framework, with Vercel Sandbox. The agent is research-only: it cannot comment, close, push, or deploy, and it ignores prompt-injection instructions in issue text. It ran on GPT-5.6 Luna, with investigations averaging about 30 minutes and up to 200 concurrent eve sessions.",
      "By September 4, 1,462 issues were closed across the repository, including some outside this review. The reasons were Already fixed 543 (37%), Duplicate 278 (19%), Expected behavior 237 (16%), No longer reproducible 89 (6%), Unsupported or obsolete 66 (5%), and Other 249 (17%). The Maintainer Agent also includes reproduction, verification, e2e_test, and fix agents, and code changes still need human review before merge. Each week, closability researches up to 100 stale open issues, and the team is starting auto-close for the clearest cases (a score of 80 or higher plus a second agent, up to 25 a week) with a reopen window.",
      "The closability review is about the same Next.js codebase you start from in Chapter 1.",
    ],
    source: {
      title: "How we closed 1,500 GitHub issues in one month",
      url: "https://nextjs.org/blog/how-we-closed-1500-github-issues",
      publisher: "Next.js",
    },
  },
  {
    slug: "nextjs-upcoming-security-release-sept-30-2026",
    title: "Next.js plans Sept 30 security release (16.3.7 / 15.5.27)",
    publishedAt: "2026-09-24T12:00:00.000Z",
    tags: ["nextjs", "security", "course"],
    relatedChapters: ["ch1", "ch5"],
    intro: [
      "Next.js is preparing a scheduled security release for September 30, 2026. The September 30 release will address nine vulnerabilities: one critical, two high, five medium, and one low. The team plans to publish 16.3.7 and 15.5.27 with full advisories covering impact, affected versions, and upgrade instructions.",
      "The post recommends upgrading to a patched version once the release is available. It points to Vercel's Open Source Bug Bounty for contributing, and to security@vercel.com for questions.",
      "That upgrade is the same framework hygiene as Chapter 1 and the Node package and dependency upgrades in Chapter 5.",
    ],
    source: {
      title: "Upcoming Next.js September Security Release",
      url: "https://nextjs.org/blog/upcoming-nextjs-security-release-september-2026",
      publisher: "Next.js",
    },
  },
  {
    slug: "nextjs-security-update-sept-22-2026",
    title: "Next.js 16.3.6 / 15.5.26: patch Node.js ImageResponse RCE now",
    publishedAt: "2026-09-23T12:00:00.000Z",
    tags: ["nextjs", "security", "course"],
    relatedChapters: ["ch1", "ch5"],
    intro: [
      "On September 22, 2026, the Next.js team published an out-of-band security update. Next.js 16.3.6 (Active LTS) and 15.5.26 (Maintenance LTS) upgrade upstream dependencies, including Satori, to address an issue that could lead to remote code execution. Version 15.5.26 includes related hardening, but Next.js 15.x is not affected by the remote code execution issue.",
      "The critical issue is remote code execution in the Node.js ImageResponse path in next/og (GHSA-vcvr-r3jv-pc5j), with related upstream advisory GHSA-wx4j-mvgx-mqwp for Satori. Next.js versions >=16.2.0 and <16.3.6 are affected. Improper escaping in SVG output from Satori could lead to RCE via other upstream dependencies; the fix upgrades those dependencies. Applications using the Edge ImageResponse implementation are not affected.",
      "That upgrade is the same framework and dependency hygiene as Chapter 1 and the Node packages in Chapter 5; follow the original Next.js post for upgrade commands and advisory details.",
    ],
    source: {
      title: "Next.js Security Update for a Critical Upstream Issue",
      url: "https://nextjs.org/blog/nextjs-security-update-september-22-2026",
      publisher: "Next.js",
    },
  },
  {
    slug: "ai-gateway-jev-fastest-adopted",
    title: "Jev: fastest first-day adoption on Vercel AI Gateway",
    publishedAt: "2026-09-23T12:00:00.000Z",
    tags: ["ai", "course"],
    relatedChapters: ["ch1", "ch5"],
    intro: [
      "On September 18, 2026, Amelia Charles, Harpreet Arora, and Eric Dodds reported that within 24 hours of launching on AI Gateway, Jev from TypeSafe AI reached more than twice as many paid teams as any previous model launch. By hour 24, nearly 13% of paid teams were using it — 2x the GPT-5.6 family and more than 6x Fable 5.1's share. The post also notes Jev is free on AI Gateway until September 25.",
      "Jev was introduced on September 15 as a probabilistic decision model: an application sends context and questions, and Jev returns typed choices, scores, or true-or-false answers with probabilities. TypeSafe AI reports that in its own workflow evaluations Jev was up to 194 times faster and 445 times cheaper than language models.",
      "Those Gateway numbers come from the same Vercel platform you already deploy to in Chapter 1 (and the Node server work in Chapter 5).",
    ],
    source: {
      title: "Jev is the fastest-adopted model in AI Gateway history",
      url: "https://vercel.com/blog/ai-gateway-jev-model-launch",
      publisher: "Vercel",
    },
  },
  {
    slug: "featured-100k-media-pitches-vercel",
    title: "Featured: 100K media pitches a month with three engineers on Vercel",
    publishedAt: "2026-09-23T12:00:00.000Z",
    tags: ["nextjs", "ai", "course"],
    relatedChapters: ["ch1", "ch5"],
    intro: [
      "On September 11, 2026, Susan Aziz (with Eric Dodds) described how Featured, a co-pilot for public relations, runs on Vercel with three engineers supporting three brands and more than 100,000 users. The team migrated 374 Sanity sites from AWS Elastic Beanstalk to Vercel, routes chat across 17 models through AI SDK and AI Gateway, and replaced custom long-running job infrastructure with Workflow SDK. Agents deliver more than 100,000 media pitches per month.",
      "Chat became the primary interface via eve and the useEveAgent hook, with durable sessions, streaming, tool calls, and approval prompts, and model calls through AI Gateway. Founder Brett Farmiloe frames Vercel's developer experience as the multiplier that lets three engineers move like a much larger team.",
      "Featured's workflow is the same Vercel deploy path you already use in Chapter 1 (and the Node server work in Chapter 5).",
    ],
    source: {
      title: "How Featured's users make 100K media pitches per month on Vercel",
      url: "https://vercel.com/blog/how-featureds-users-make-100k-media-pitches-per-month-on-vercel",
      publisher: "Vercel",
    },
  },
  {
    slug: "nextjs-upcoming-security-release-sept-22-2026",
    title: "Next.js plans Sept 22 out-of-band security release (16.3.6 / 15.5.26)",
    publishedAt: "2026-09-22T12:00:00.000Z",
    tags: ["nextjs", "security", "course"],
    relatedChapters: ["ch1", "ch5"],
    intro: [
      "Next.js announced an upcoming out-of-band security update for a critical issue identified in an upstream dependency. The team plans to publish Next.js 16.3.6 and 15.5.26 on September 22, 2026. The full advisory GHSA-vcvr-r3jv-pc5j will publish with the update and will cover impact, affected versions, and upgrade instructions.",
      "Upgrade to 16.3.6 or 15.5.26 as soon as those releases are available. For questions about the Vercel Open Source Bug Bounty program, the post points to security@vercel.com.",
      "That upgrade is the same framework and dependency hygiene as Chapter 1 and the Node packages in Chapter 5; follow the original Next.js post and the advisory when it publishes for affected versions and upgrade steps.",
    ],
    source: {
      title: "Upcoming Next.js Security Update for a Critical Upstream Issue",
      url: "https://nextjs.org/blog/upcoming-nextjs-security-release-september-22-2026",
      publisher: "Next.js",
    },
  },
  {
    slug: "ai-gateway-production-index-september-2026",
    title: "AI Gateway Index: open-weight models hit 56% of token volume",
    publishedAt: "2026-09-22T12:00:00.000Z",
    tags: ["ai", "course"],
    relatedChapters: ["ch1", "ch5"],
    intro: [
      "On September 17, 2026, Amelia Charles and Eric Dodds published the September AI Gateway Production Index, covering data through August 2026. Open-weight models ran 56% of AI Gateway tokens in August, up from 7% in December — the first month they held a majority. Average price per token fell 23.2% in August, the third straight monthly drop; among teams with more than 10M tokens in both months, the median team paid 7.6% less.",
      "On frontier spend, Fable 5 share of gateway spend fell from 13.2% in July to 4.9% in August as Opus 5 rose to 22.5%, while Anthropic kept 64% of all spend. A special report notes GPT-6 Astra launched on Gateway September 3 and within two days took a third of OpenAI spend; over its first twelve days Astra was 7.7% of all gateway spend versus Fable 5.1 at 3.7% (Fable 5.1 launched September 1 at the same price). A September 18 note in the post adds that Jev became the fastest-adopted model in Gateway history, reaching about 13% of paid teams in the first 24 hours.",
      "Those Gateway numbers come from the same Vercel platform you already deploy to in Chapter 1 (and the Node server work in Chapter 5).",
    ],
    source: {
      title:
        "Open-weight models take 56% of token volume, Astra doubles Fable 5.1 spend",
      url: "https://vercel.com/blog/ai-gateway-production-index-september-2026",
      publisher: "Vercel",
    },
  },
  {
    slug: "delphi-100-deploys-day-python-vercel",
    title: "Delphi: 100+ production deploys a day with Python backend on Vercel",
    publishedAt: "2026-09-22T12:00:00.000Z",
    tags: ["nextjs", "ai", "course"],
    relatedChapters: ["ch1", "ch5"],
    intro: [
      "On September 15, 2026, Susan Aziz and Kevin Sundstrom described how Delphi, which builds digital minds, ships on Vercel. Founding engineer Spencer Schoeben emphasized needing excellent developer and agentic experience. The frontend ran on Vercel from day one; about six months ago the team rebuilt its Python backend on Vercel after onboarding pain with AWS, ECS, Docker, and a local database.",
      "With 10 engineers and no dedicated infra role, Delphi does 100+ production deploys a day behind feature flags, and product and design ship too. Workflows handle long-running work and Queues handle background jobs: engineers write functions in the codebase and Vercel provisions them on deploy. Preview deployments make cloud agents' work reviewable via a live URL; agents use the SDK, MCP, and CLI. An internal Sandbox agent supports customer success over Slack, and chat traffic goes through AI Gateway with per-mind model routing and failover.",
      "Delphi's cadence is the same Vercel deploy path you already use in Chapter 1 (and the Node server work in Chapter 5).",
    ],
    source: {
      title: "How Delphi ships 100 times a day with its Python backend on Vercel",
      url: "https://vercel.com/blog/how-delphi-ships-100-times-a-day-with-its-python-backend-on-vercel",
      publisher: "Vercel",
    },
  },
  {
    slug: "tailscale-aperture-ai-gateway",
    title: "Tailscale Aperture: model routing on Vercel AI Gateway and Sandbox",
    publishedAt: "2026-09-21T12:00:00.000Z",
    tags: ["ai", "course"],
    relatedChapters: ["ch1", "ch5"],
    intro: [
      "On September 11, 2026, Eric Dodds and Susan Aziz described how Tailscale built Aperture, a customer-facing model router that applies tailnet identity to AI model access. Add someone to the private network and they can use approved models; remove them and access disappears. Co-founder David Carney framed Tailscale as a networking company that chose not to rebuild provider routing; Remy Guercio leads the Aperture product.",
      "Aperture sits on Vercel AI Gateway — one API for hundreds of models, with cost and usage in responses and zero data retention options including per-request zeroDataRetention — plus Vercel Sandbox for agent execution. The post uses the lethal trifecta framing for agents that can read private data, act on it, and reach the public internet, and mitigates that with an isolated sandbox plus identity controls. There is no cost markup on AI Gateway: customers pay the same rates as going direct. Tailscale migrated its own internal AI traffic to Gateway with a switch and reported that nobody noticed, going from prototype to paying customers in months.",
      "The model router runs on the same Vercel deploy path you already use in Chapter 1 (and the Node server work in Chapter 5).",
    ],
    source: {
      title: "How Tailscale built a customer-facing model router on AI Gateway",
      url: "https://vercel.com/blog/how-tailscale-built-a-customer-facing-model-router-on-ai-gateway",
      publisher: "Vercel",
    },
  },
  {
    slug: "vercel-design-md-agents",
    title: "design.md: teach agents on-brand pages outside the repo",
    publishedAt: "2026-09-21T12:00:00.000Z",
    tags: ["ai", "course"],
    relatedChapters: ["ch1"],
    intro: [
      "On August 31, 2026, John Phamous explained how Vercel agents build on-brand pages when they cannot read the repo. The internal product-design skill works in-repo; design.md is a single public URL for reports, proposals, and one-offs that live outside the codebase. A naive port of that skill into one prompt failed because models interpreted vague design language differently without real components nearby.",
      "The team rebuilt around seven fixed eval prompts — usage report, renewal proposal, benchmark, planning page, build-vs-buy, security brief, and a deck — and measured outputs. The system has three parts: design.md guidance, a public stylesheet of classes and tokens (the agent documents class names; CSS loads in the browser so it does not fill model context), and an evaluation loop with deterministic checks plus human review. On matched trials, known mechanical failures fell from 91 without design.md to 39 with it (57% fewer). The sample is small, and pages can still have ship-blocking issues. Weekly feedback from Slack @design-agent (eve), GitHub, and Figma keeps the file current.",
      "The eval loop and public stylesheet are how the agent stays on-brand, next to the React you build in Chapter 1.",
    ],
    source: {
      title: "How our agents build on-brand pages with design.md",
      url: "https://vercel.com/blog/how-our-agents-build-on-brand-pages-with-design-md",
      publisher: "Vercel",
    },
  },
  {
    slug: "libheif-avif-rce-disclosure",
    title: "libheif AVIF RCE: from Next.js image opt to upstream fix",
    publishedAt: "2026-09-21T12:00:00.000Z",
    tags: ["nextjs", "security", "course"],
    relatedChapters: ["ch1"],
    intro: [
      "On September 18, 2026, Karim Rahal wrote up how Vercel reproduced, disclosed, and helped fix a libheif remote-code-execution bug that first showed up as an apparent Next.js image-optimization RCE. Hacktron reported the issue; the root cause was the upstream AVIF decoder. The request path was next/image to /_next/image to sharp to libvips to libheif.",
      "The timeline in the post is August 11-12 for the report and reproduce, August 13 for a Vercel platform mitigation that disabled AVIF on the Image Optimization Service, August 19 for coordination with libvips, August 24 for partner notification, and August 25 for the Next.js security release that disabled AVIF optimization. The same day, libheif v1.23.2 remediated the RCE. Self-hosted apps needed that Next.js release; Vercel-hosted apps were mitigated earlier at the platform layer. The write-up notes rising open-source vulnerability volume in 2026 and credits Hacktron plus the sharp, libvips, and libheif maintainers.",
      "The image-optimization chain starts in the Next.js app you set up in Chapter 1; the original Vercel post has the timeline, and this write-up is separate from the August 2026 security release.",
    ],
    source: {
      title:
        "Reproducing, disclosing, and fixing the libheif vulnerability with Hacktron and the maintainers",
      url: "https://vercel.com/blog/reproducing-disclosing-and-fixing-the-libheif-vulnerability-with-hacktron-and-the-maintainers",
      publisher: "Vercel",
    },
  },
  {
    slug: "vercel-fluid-compute-any-shape",
    title: "Vercel Fluid: one compute layer for functions, sandboxes, and builds",
    publishedAt: "2026-09-17T12:00:00.000Z",
    tags: ["nextjs", "ai", "course"],
    relatedChapters: ["ch1", "ch5"],
    intro: [
      "On September 1, 2026, Luke Phillips-Sheard published Compute that takes any shape on the Vercel blog. Fluid is Vercel's unified compute layer: it assembles the machine a workload needs, swaps configuration on the fly, and absorbs burst capacity. Builds ran on it first, then sandboxes, and now functions; the post says if you have shipped on Vercel you have already been on Fluid.",
      "The post cites more than 15 million builds a day, 25 million sandboxes a week, and a trillion requests a month. Building blocks include Hive, which provisions isolated machines; Fluid images and VHS snapshots, which resume custom environments rather than cold-booting; and Vercel Drives, portable storage that outlives the machine (sandboxes today, private beta). Many requests share one instance, and Active CPU pricing means you pay for CPU while code runs, not while waiting on a database or model. The write-up is framed for agents that need fast, isolated machines with their own environment and state that outlives compute.",
      "Fluid is the compute under the same Vercel deploy path you already use in Chapter 1 (and the Node server work in Chapter 5).",
    ],
    source: {
      title: "Compute that takes any shape",
      url: "https://vercel.com/blog/fluid-compute-takes-any-shape",
      publisher: "Vercel",
    },
  },
  {
    slug: "claude-code-vs-copilot-vs-cursor-2026",
    title: "Claude Code vs Copilot vs Cursor: pick the tool that matches how you work",
    publishedAt: "2026-09-17T12:00:00.000Z",
    tags: ["ai", "course"],
    relatedChapters: ["ch1"],
    intro: [
      "On September 7, 2026, GeekyGoo published a comparison of three AI coding tools and the philosophies behind them. GitHub Copilot adds AI to the IDE you already use; Cursor is an AI-first fork of VS Code; Claude Code is a terminal-native agent from Anthropic.",
      "The post's 30-second verdict: cheapest autocomplete in your current IDE points to Copilot; the most fluid AI-native editing points to Cursor; serious multi-file, agent, or CI work that should stay editor-agnostic points to Claude Code. Late-2026 prices the post lists (check official pages, they change) are Copilot Free / Pro at $10 per month, Cursor Free / Pro at $20 per month, and Claude Code through Claude Pro at $20 per month with no standalone free tier. The honest takeaway is that many professionals combine tools rather than picking only one.",
      "The verdict is about the editor; you are still writing the Next.js and React from Chapter 1.",
    ],
    source: {
      title:
        "Claude Code vs. GitHub Copilot vs. Cursor: which AI coding tool actually fits your workflow (2026)",
      url: "https://www.geekygoo.com/blog/claude-code-vs-github-copilot-vs-cursor/",
      publisher: "GeekyGoo",
    },
  },
  {
    slug: "shai-hulud-npm-resurfaces-111-days",
    title: "Shai-Hulud npm worm resurfaces after 111 days despite publish-time scanning",
    publishedAt: "2026-09-17T12:00:00.000Z",
    tags: ["security", "course"],
    relatedChapters: ["ch5"],
    intro: [
      "On September 7, 2026, Charlie Eriksen wrote that the Shai-Hulud npm worm had resurfaced. The May 19, 2026 wave hit @antv with 639 malicious versions in an hour. After 111 days of silence, the same payload hash (e37e3ddeeaaa9e0c4fdbcb829b4895a6521031c80053fc436625b61e6ee5b1a6) reappeared in four packages published within the same hour: feishu-docx-mcp@0.3.2, bmc-i18n-extract-cli@1.1.1, blueai-cli@0.7.0, and bmc-translate-utils@1.1.1.",
      "npm had rolled out publish-time malware scanning in July, holding packages for 5 to 15 minutes before they become installable. Aikido argues that an exact match against a known-malicious hash is the easy case and still got missed. Indicators named in the post include a C2 host written as t[.]m-kosche[.]com, a preinstall script of bun run index.js, and persistence via .vscode/tasks.json and .claude/settings.json.",
      "Unexpected install scripts and unfamiliar packages fit the Node dependency hygiene in Chapter 5; the original Aikido post has the full indicator list.",
    ],
    source: {
      title: "Shai-Hulud Rises From the Dead after 111 days",
      url: "https://www.aikido.dev/blog/shai-hulud-npm-resurfaces",
      publisher: "Aikido Security",
    },
  },
  {
    slug: "vercel-flat-rate-cdn",
    title: "Vercel Flat Rate CDN: predictable Pro billing for traffic spikes",
    publishedAt: "2026-09-16T12:00:00.000Z",
    tags: ["nextjs", "course"],
    relatedChapters: ["ch1"],
    intro: [
      "On September 8, 2026, Jas Garcha and Eric Dodds announced Flat Rate CDN for Vercel Pro teams: a fixed monthly CDN bill with spike protection instead of pure usage-based CDN charges. New Pro teams get Flat Rate CDN by default; existing Pro teams can opt in. Usage is tracked at the team level across all projects.",
      "One fixed monthly fee covers CDN Requests, Fast Data Transfer, Blob Data Transfer, and Observability events from CDN requests. Example tiers in the post include Flat Rate CDN 1M (included with Pro: 1M requests / 1 TB), 10M ($20), 50M ($100), and 150M ($300). The post says temporary spikes do not raise the bill, and that Vercel rightsizes the tier from sustained usage rather than capping or degrading the site when traffic goes viral. Teams can still opt out to pay-as-you-go CDN.",
      "The fixed CDN bill is about the same Vercel deploy path you already use in Chapter 1.",
    ],
    source: {
      title: "Introducing Flat Rate CDN",
      url: "https://vercel.com/blog/introducing-flat-rate-cdn",
      publisher: "Vercel",
    },
  },
  {
    slug: "openai-agents-api",
    title: "OpenAI Agents API: Codex harness for cloud agents in public beta",
    publishedAt: "2026-09-16T12:00:00.000Z",
    tags: ["ai", "course"],
    relatedChapters: ["ch1"],
    intro: [
      "On September 10, 2026, OpenAI introduced the Agents API in public beta. It exposes the same harness and infrastructure that powers Codex so developers can create cloud agents through an API: specify the task, model, tools, and environment, then let OpenAI host and maintain the harness.",
      "You choose where the agent runs — an OpenAI-hosted sandbox, your own infrastructure, or partner sandboxes (the post names providers including Blaxel, Cloudflare, Daytona, DigitalOcean, E2B, Modal, Oracle, Runloop, and Vercel). The harness covers long-session context compaction, tool search and programmatic tool calling (including MCP, custom functions, and web search), and optional multi-agent subagent delegation. The post says the API is powered by the open-source Codex harness, with no extra fee beyond tokens and tools used.",
      "The hosted harness is another way to run an agent around the Next.js app you build in Chapter 1.",
    ],
    source: {
      title: "Introducing the Agents API",
      url: "https://openai.com/index/introducing-the-agents-api/",
      publisher: "OpenAI",
    },
  },
  {
    slug: "vercel-run-sdk",
    title: "Vercel Run SDK: sandboxed JavaScript for agent-generated code",
    publishedAt: "2026-09-16T12:00:00.000Z",
    tags: ["ai", "security", "course"],
    relatedChapters: ["ch1", "ch5"],
    intro: [
      "On August 25, 2026, Aayush Kapoor published Introducing Run SDK on the Vercel blog. The package runs untrusted JavaScript or type-stripped TypeScript in a fresh QuickJS context inside a worker thread, with no direct route to Node.js or the network. Applications expose narrow hostFunctions that become callable globals inside the sandbox; credentials and service clients stay in the host.",
      "Host functions can interrupt a run for human approval or authentication via getHostFunctionContext().interrupt, then resume with a signed token so settled host calls are not repeated. createRunner() sets shared limits such as timeoutMs and memoryLimitBytes. The post states the Run SDK powers code-mode tool execution in the AI SDK, supports Node.js 22.13+ and Bun (install with pnpm add run), and that OS-level isolation still belongs in Vercel Sandbox rather than this in-process QuickJS boundary.",
      "Keeping credentials in host functions, outside the sandbox, fits the Node server work in Chapter 5 and the Next.js app in Chapter 1.",
    ],
    source: {
      title: "Introducing Run SDK: secure eval for your agents",
      url: "https://vercel.com/blog/introducing-run",
      publisher: "Vercel",
    },
  },
  {
    slug: "vercel-cdn-metadata-shards-91",
    title: "Vercel CDN: indexed metadata shards cut P99 lookup latency 91%",
    publishedAt: "2026-09-15T12:00:00.000Z",
    tags: ["nextjs", "course"],
    relatedChapters: ["ch1"],
    intro: [
      "On September 10, 2026, Tim Caswell, Steven Salat, and Luba Kravchenko described how Vercel cut CDN metadata lookup latency. The CDN runs on average over 80 million routing instructions per second, and metadata lookups decide which paths exist and how to serve them. The team moved from per-path metadata objects to bounded indexed shards of about 200 KB, using JSONL plus inline indexes so one fetch warms many paths while lookups parse only the needed record.",
      "Production measurements on August 5-12, 2026 traffic show P99 metadata lookup latency falling from 215.8 ms to 19.1 ms (91% lower) and the average from 8.59 ms to 1.81 ms (79% lower). Deployments built after July 17, 2026 already use the new shards; older deployments need a redeploy. The Build Output API contract is unchanged, and the change also saved about 16.6 seconds of redundant metadata upload work, making the deploy step about 10% faster overall. That routing is the same Vercel deploy path you already use in Chapter 1, and a redeploy can pick up the platform change without app code changes.",
    ],
    source: {
      title: "How we cut CDN metadata lookup latency by 91%",
      url: "https://vercel.com/blog/how-we-cut-cdn-metadata-lookup-latency-by-91-percent",
      publisher: "Vercel",
    },
  },
  {
    slug: "cursor-projects-coordinator",
    title: "Cursor Projects: coordinator agents for features, migrations, and gardening",
    publishedAt: "2026-09-15T12:00:00.000Z",
    tags: ["ai", "course"],
    relatedChapters: ["ch1"],
    intro: [
      "On September 10, 2026, Alexi Robbins and Fredrika Lindh introduced Cursor Projects on the product blog, rolling out in beta. Projects take on larger bodies of work such as a feature, a migration, or a full app: they keep context over months, delegate to thousands of subagents, and can run recurring work without being prompted. You chat with a Projects coordinator that directs other agents rather than writing code itself. Runs are cloud by default on their own computer so closing a laptop does not stop the work, agents share context files, and subscriptions cover Slack, a schedule, and pull requests or CI.",
      "Cursor reports that new users merge 30% more pull requests, and that users who primarily use Projects merge six times as many — those figures are Cursor's own reporting. The post describes three patterns: feature work, migrations that span hundreds of pull requests, and ongoing gardening such as a design-system Project watching pull requests.",
      "The coordinator still depends on the Next.js and React you learn in Chapter 1.",
    ],
    source: {
      title: "Introducing Projects",
      url: "https://cursor.com/blog/projects",
      publisher: "Cursor",
    },
  },
  {
    slug: "express-august-2026-security-releases",
    title: "Express August 2026 security releases: hbs, multer, and morgan",
    publishedAt: "2026-09-15T12:00:00.000Z",
    tags: ["security", "course"],
    relatedChapters: ["ch5"],
    intro: [
      "On August 31, 2026, Ulises Gascon published August 2026 security releases on the Express blog. The releases are hbs 4.3.0, multer 2.3.0, and morgan 1.12.0, addressing six vulnerabilities.",
      "The post names CVE-2026-16231 (hbs async helper XSS, High); CVE-2026-77037, CVE-2026-77078, and CVE-2026-82333 (multer denial-of-service and resource issues, High); CVE-2026-15603 (morgan Unicode log forging, Medium); and CVE-2026-77063 (multer async fileFilter size-limit bypass, Low). The recommended action is to upgrade with npm update hbs multer morgan, or bump those packages. Multipart upload middleware and request logging fit the Node dependency hygiene in Chapter 5; follow the original Express post for the full CVE list and upgrade notes.",
    ],
    source: {
      title: "August 2026 Security Releases",
      url: "https://expressjs.com/en/blog/2026-08-31-security-releases/",
      publisher: "Express.js",
    },
  },
  {
    slug: "react-19-3",
    title: "React 19.3: View Transitions, Fragment Refs, browser(), and Trusted Types",
    publishedAt: "2026-09-14T16:00:00.000Z",
    tags: ["react", "course"],
    relatedChapters: ["ch1", "ch3"],
    intro: [
      "On September 9, 2026, the React Team announced that React 19.3 is on npm. View Transitions and Fragment Refs, shared as experimental APIs last year, are stable in this release.",
      "The ViewTransition component animates elements as they enter, exit, move, or resize using the browser View Transition API. You can pass a ref to a Fragment to get a FragmentInstance for working with sibling DOM children as a group. A component can call use(browser()) to opt out of server-side rendering: the nearest Suspense fallback shows on the server, then the component renders after hydration. React 19.3 also passes Trusted Types values through without string coercion so a Content-Security-Policy require-trusted-types-for policy can protect injection sinks such as innerHTML.",
      "View Transitions, Fragment refs, and the other stable APIs pair with the React components in Chapter 1 and the client UI in Chapter 3; this repo still pins an earlier React.",
    ],
    source: {
      title: "React 19.3",
      url: "https://react.dev/blog/2026/09/09/react-19-3",
      publisher: "React",
    },
  },
  {
    slug: "ai-sdk-7-agent-platform",
    title: "AI SDK 7: agents, tools, and realtime beyond text",
    publishedAt: "2026-09-14T16:00:00.000Z",
    tags: ["ai", "course"],
    relatedChapters: ["ch1"],
    intro: [
      "On June 25, 2026, Vercel published AI SDK 7, the TypeScript SDK they describe as the layer for building AI applications, features, frameworks, and agents across model providers. The post frames the release as production depth for agent work: developing agents (reasoning control, typed tool and runtime context, provider file and skill uploads, MCP Apps, and a terminal UI), running them (tool approvals, durable WorkflowAgent, timeouts, and sandbox sessions), integrating established harnesses, and observing runs with telemetry and lifecycle events.",
      "The same announcement also covers experimental provider-agnostic realtime voice sessions and generateVideo. A v7 codemod is mentioned for upgrades from AI SDK 6.",
      "If you try the SDK, start from this release's APIs; they sit beside the Next.js app in Chapter 1, rather than last year's AI SDK surface.",
    ],
    source: {
      title: "AI SDK 7",
      url: "https://vercel.com/blog/ai-sdk-7",
      publisher: "Vercel",
    },
  },
  {
    slug: "nextjs-security-middleware-proxy",
    title: "Next.js security: Middleware and Proxy are not the only authorization layer",
    publishedAt: "2026-09-14T16:00:00.000Z",
    tags: ["nextjs", "security", "course"],
    relatedChapters: ["ch1", "ch5"],
    intro: [
      "On September 14, 2026, iSyncEvolution published a CTO-oriented guide to Next.js Middleware and Proxy authorization risk. It reviews CVE-2025-29927, a critical Middleware authorization bypass (CVSS 9.1) patched in releases including 12.3.5, 13.5.9, 14.2.25, and 15.2.3, plus later 2026 Middleware/Proxy bypasses disclosed in May (App Router segment-prefetch, Pages Router i18n, dynamic route parameters) and July (certain App Router apps using Turbopack and a single i18n locale in the 16.0.x–16.2.x range).",
      "The through-line is architectural: do not treat Middleware or, in Next.js 16, proxy.ts as the only authorization layer. The guide repeats the recommended workaround — enforce authorization in server-side page, Route Handler, Server Action, or data-access logic — and notes that renaming middleware.ts to proxy.ts is not itself a security migration.",
      "This site already uses a proxy file for request handling, the same app boundary as Chapter 1, and that still does not replace the server-side checks in Chapter 5.",
    ],
    source: {
      title: "Next.js Security Best Practices: CTO Guide to Middleware & Proxy Risks",
      url: "https://www.isyncevolution.com/blog/nextjs-security-best-practices",
      publisher: "iSyncEvolution",
    },
  },
  {
    slug: "august-2026-nextjs-security-release",
    title: "August 2026 Next.js security release: patch 16.3.3",
    publishedAt: "2026-08-25T18:00:00.000Z",
    tags: ["nextjs", "security", "course"],
    relatedChapters: ["ch1", "ch5"],
    intro: [
      "On August 25, 2026, the Next.js team published a security release and asked everyone to patch immediately. Updates landed in v16.3.3 (Active LTS) and v15.5.24 (Maintenance LTS) after an extra critical issue in an upstream dependency moved the date forward.",
      "Two issues are called out: unauthenticated remote code execution in the Image Optimization API when using AVIF (a vulnerability in libheif used by sharp; the patched releases disable AVIF optimization until an upstream fix lands), and a Windows-only unauthenticated RCE when an app uses both the Pages Router and the App Router without Cache Components. Linux and macOS are not affected by the Windows issue; the post says there is no known workaround for affected Windows-hosted apps.",
      "Most of you deploy this course on Vercel (Linux), the same deploy path as Chapter 1 (and Node server work in Chapter 5), but the habit still matters: when the Next.js blog says patch ASAP, bump next and redeploy. This digest is not a substitute for the advisory — follow the original post and the linked GHSA/CVE entries.",
    ],
    source: {
      title: "August 2026 Security Release",
      url: "https://nextjs.org/blog/august-2026-security-release",
      publisher: "Next.js",
    },
  },
  {
    slug: "nextjs-16-3-instant-navigations",
    title: "Next.js 16.3: Instant Navigations and a faster everyday toolchain",
    publishedAt: "2026-08-03T17:00:00.000Z",
    tags: ["nextjs", "react", "course"],
    relatedChapters: ["ch1", "ch3"],
    intro: [
      "Next.js 16.3 is the framework release this course site already sits on. The official post highlights Instant Navigations — an opt-in suite that aims for SPA-like clicks without giving up the server-driven App Router — plus quieter wins you will feel in lab: lower next dev memory (up to 90% less RAM on long sessions), faster rebuilds via disk cache, TypeScript 7 type-checking during next build, and up to 22% more requests under load after App Router SSR switched to native Node streams.",
      "The practical takeaway is upgrade hygiene and the App Router navigation model in Chapter 1 and Chapter 3. Instant Navigations stays opt-in through cacheComponents and partialPrefetching in next.config.ts. The original notes on Instant Insights, Partial Prefetching, and the Playwright instant() helper spell out the caching behavior.",
      "The same post also points at versioned docs for AI agents (the AGENTS.md block next dev writes) and a companion write-up on agent tooling, alongside the Chapter 1 and Chapter 3 navigation work.",
    ],
    source: {
      title: "Next.js 16.3",
      url: "https://nextjs.org/blog/next-16-3",
      publisher: "Next.js",
    },
  },
  {
    slug: "nextjs-16-3-ai-improvements",
    title: "Next.js 16.3 AI improvements: version-matched docs and agent Skills",
    publishedAt: "2026-06-26T15:00:00.000Z",
    tags: ["nextjs", "ai", "course"],
    relatedChapters: ["ch1"],
    intro: [
      "Before 16.3 went stable, the Next.js team published a preview-era post about designing the framework for agent-driven development. The through-line is keeping coding agents on this version of Next.js instead of stale training data: next dev writes a version-matched AGENTS.md pointer at the bundled docs in node_modules/next/dist/docs/.",
      "The post also describes first-party Skills for multi-step workflows (next-dev-loop, Cache Components adoption and optimizer), agent-browser React introspection, Instant Insights fix menus with copy-ready prompts, a smaller DevTools MCP server, and docs-as-Markdown (append .md to any docs URL).",
      "If you already use Cursor or another agent, read the local Next.js docs the repo points at — the same App Router you use in Chapter 1 — and do not assume last year's App Router APIs still apply.",
    ],
    source: {
      title: "Next.js 16.3: AI Improvements",
      url: "https://nextjs.org/blog/next-16-3-ai-improvements",
      publisher: "Next.js",
    },
  },
];
